// Chat Action Constants
export const CLEAR_STORE = 'CLEAR_STORE';
export const ADD_NEW_CHAT = 'ADD_NEW_CHAT';
export const CHANGE_LOGIN_STATUS = 'CHANGE_LOGIN_STATUS';
export const UPDATE_CHAT_LIST = 'UPDATE_CHAT_LIST';
export const SELECT_CURRENT_CHAT = 'SELECT_CURRENT_CHAT';
export const REFRESH_CHAT_LIST = 'REFRESH_CHAT_LIST';
export const ADD_INITIAL_MESSAGES = 'ADD_INITIAL_MESSAGES';
export const IMPLEMENT_STORE = 'IMPLEMENT_STORE';
